// src/components/StartView.vue
<script setup>
const props = defineProps({
  stepData: Object,
  handleOptionClick: Function
})
</script>

<template>
  <div class="wrapper">
    <div class="content-start">
      <h1 class="title-start">Наедине с пламенем</h1>
      <div class="texts-start">
        <p v-for="(text, index) in stepData.texts" v-bind:key="index" class="text">{{ text }}</p>
      </div>
      <div class="buttons">
        <button
          v-for="(option, index) in stepData.options"
          type="button"
          v-bind:key="index"
          v-on:click="handleOptionClick(option.nextStep)"
        >
          {{ option.text }}
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped></style>

// src/components/StartView.jsx
const StartView = ({ stepsData, handleOptionClick }) => {
  const { texts, options } = stepsData;
  return (
    <div className="wrapper">
      <div className="content-start">
        <h1 className="title-start">Наедине с пламенем</h1>
        <div className="texts-start">
          {texts.map((text, index) => (
            <p key={index} className="text">
              {text}
            </p>
          ))}
        </div>
        <div className="buttons">
          {options.map((option, index) => (
            <button
              type="button"
              key={index}
              onClick={() => handleOptionClick(option.nextStep)}
            >
              {option.text}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};

export default StartView;
